// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNGq5rTeEUvuJRGHYf5-DYVowFXgOx0IU',
    appId: '1:1098307325660:web:2e3564843477cfd987ae19',
    messagingSenderId: '1098307325660',
    projectId: 'cauldron-rop',
    authDomain: 'cauldron-rop.firebaseapp.com',
    storageBucket: 'cauldron-rop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY3FNRqXb-VuKqMBNXIRNWH3N8y6m8fY8',
    appId: '1:1098307325660:android:27173bcdc2cde66387ae19',
    messagingSenderId: '1098307325660',
    projectId: 'cauldron-rop',
    storageBucket: 'cauldron-rop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRGmT_dfikNHcMRLsQFPo7lvlIS8BlANU',
    appId: '1:1098307325660:ios:14cadce206f558c587ae19',
    messagingSenderId: '1098307325660',
    projectId: 'cauldron-rop',
    storageBucket: 'cauldron-rop.appspot.com',
    iosBundleId: 'com.example.cauldron',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRGmT_dfikNHcMRLsQFPo7lvlIS8BlANU',
    appId: '1:1098307325660:ios:1cf67ce5ef27924487ae19',
    messagingSenderId: '1098307325660',
    projectId: 'cauldron-rop',
    storageBucket: 'cauldron-rop.appspot.com',
    iosBundleId: 'com.example.cauldron.RunnerTests',
  );
}
